ALTER TABLE [dbo].[QRTZ_CRON_TRIGGERS] DROP CONSTRAINT [FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS];
ALTER TABLE [dbo].[QRTZ_SIMPLE_TRIGGERS] DROP CONSTRAINT [FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS];
ALTER TABLE [dbo].[QRTZ_SIMPROP_TRIGGERS] DROP CONSTRAINT [FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS];
ALTER TABLE [dbo].[QRTZ_TRIGGERS] DROP CONSTRAINT [FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS];

DROP TABLE [dbo].[QRTZ_CRON_TRIGGERS];
DROP TABLE [dbo].[QRTZ_SIMPLE_TRIGGERS];
DROP TABLE [dbo].[QRTZ_SIMPROP_TRIGGERS];
DROP TABLE [dbo].[QRTZ_BLOB_TRIGGERS];
DROP TABLE [dbo].[QRTZ_TRIGGERS];
DROP TABLE [dbo].[QRTZ_JOB_DETAILS];
DROP TABLE [dbo].[QRTZ_CALENDARS];
DROP TABLE [dbo].[QRTZ_FIRED_TRIGGERS];
DROP TABLE [dbo].[QRTZ_PAUSED_TRIGGER_GRPS];
DROP TABLE [dbo].[QRTZ_SCHEDULER_STATE];
DROP TABLE [dbo].[QRTZ_LOCKS];